export const products = [
  {
    id: 1,
    name: "MacBook Pro",
    description: "Apple MacBook Pro 14-inch",
    price: 1999,
    stock: 25,
    category: "Laptop",
    image: "/products/macbook.jpg",
  },
  {
    id: 2,
    name: "iPhone 16",
    description: "Latest Apple iPhone",
    price: 999,
    stock: 40,
    category: "Phone",
    image: "/products/iphone.jpg",
  },
  {
    id: 3,
    name: "Logitech MX Master 3",
    description: "Wireless ergonomic mouse",
    price: 99,
    stock: 15,
    category: "Accessories",
    image: "/products/mouse.jpg",
  },
  {
    id: 4,
    name: "Dell Monitor",
    description: "27-inch 4K monitor",
    price: 450,
    stock: 10,
    category: "Monitor",
    image: "/products/monitor.jpg",
  },
  {
    id: 5,
    name: "Dell Monitor",
    description: "27-inch 4K monitor",
    price: 450,
    stock: 10,
    category: "Monitor",
    image: "/products/monitor.jpg",
  },
  {
    id: 6,
    name: "Dell Monitor",
    description: "27-inch 4K monitor",
    price: 450,
    stock: 10,
    category: "Monitor",
    image: "/products/monitor.jpg",
  },
  {
    id: 7,
    name: "Dell Monitor",
    description: "27-inch 4K monitor",
    price: 450,
    stock: 10,
    category: "Monitor",
    image: "/products/monitor.jpg",
  },
  {
    id: 8,
    name: "Dell Monitor",
    description: "27-inch 4K monitor",
    price: 450,
    stock: 10,
    category: "Monitor",
    image: "/products/monitor.jpg",
  },{
    id: 9,
    name: "Dell Monitor",
    description: "27-inch 4K monitor",
    price: 450,
    stock: 10,
    category: "Monitor",
    image: "/products/monitor.jpg",
  },{
    id: 10,
    name: "Dell Monitor",
    description: "27-inch 4K monitor",
    price: 450,
    stock: 10,
    category: "Monitor",
    image: "/products/monitor.jpg",
  },{
    id: 11,
    name: "Dell Monitor",
    description: "27-inch 4K monitor",
    price: 450,
    stock: 10,
    category: "Monitor",
    image: "/products/monitor.jpg",
  },
];